- type: antag
  id: Changeling
  name: roles-antag-changeling-name
  antagonist: true
  setPreference: false
  objective: roles-antag-changeling-description
  requirements:
  - !type:CharacterSpeciesRequirement
    inverted: true
    species:
    - IPC
