- type: job
  id: PlanetfallTeam1SubLeader
  name: job-name-planetfall-team1-subleader
  description: job-description-planetfall-team-subleader
  playTimeTracker: ConscriptDSM
  requirements:
    - !type:CharacterOverallTimeRequirement
      min: 10000
    - !type:CharacterTraitRequirement
      inverted: true
      traits:
        - Muted
        - Blindness
        - Pacifist
        - WheelchairBound
  weight: 8
  startingGear: PlanetfallT1SubLeaderGear
  alwaysUseSpawner: true
  icon: "JobIconPFT1sublead"
  requireAdminNotify: true
  supervisors: job-supervisors-pf
  canBeAntag: false
  special:
  - !type:AddComponentSpecial
    components:
      - type: ChatRank
        rank: crescent-rank-PFSubLeader
      - type: HullrotFaction
        faction: DSM
      - type: LanguageAdder
        addSpoken:
          - Tradeband
        addUnderstood:
          - Tradeband
  access:
  - EmergencyShuttleRepealAll
  - Captain
  - HeadOfPersonnel
  - ChiefEngineer
  - ChiefMedicalOfficer
  - HeadOfSecurity
  - ResearchDirector
  - Frontier # Frontier
  - Cryogenics
  - Security
  - Detective
  - Armory
  - Brig
  - Lawyer
  - Engineering
  - Mail # Frontier
  - Medical
  - Mercenary # Frontier
  - Quartermaster
  - Salvage
  - Cargo
  - Research
  - Service
  - StationTrafficController # Frontier
  - Maintenance
  - External
  - Janitor
  - Theatre
  - Bar
  - Chemistry
  - Kitchen
  - Chapel
  - Hydroponics
  - Atmospherics
  - Command
  - Service
  - Empire

- type: startingGear
  id: PlanetfallT1SubLeaderGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitShinoharaHighsec
    shoes: ClothingShoesBootsCombat
    gloves: ClothingHandsGlovesCombat
    id: HighsecPDA
    ears: ClothingHeadsetShinohara
    pocket1: WeaponPistolLiquidator
    back: ClothingBackpackSHISatchel
    head: ClothingHeadHatShinoharaBeretUA
    outerClothing: ClothingOuterArmorShinoharaArmorHighsecUA
    belt: ClothingBeltSecurityFilled
    eyes: ClothingEyesHudSecurity

