using Content.Client.Computer;
using Content.Client.Shuttles.UI;
using Content.Client.UserInterface.Controls;
using Content.Shared._Crescent.DroneControl;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Map;
using System.Linq;

namespace Content.Client._Crescent.DroneControl;

[GenerateTypedNameReferences]
public sealed partial class DroneConsoleWindow : FancyWindow, IComputerWindow<DroneConsoleBoundUserInterfaceState>
{
    public ShuttleNavControl Radar => NavRadar;
    public Action<EntityCoordinates>? OnRadarOrder;

    // Track selected drones
    private readonly HashSet<NetEntity> _selectedDrones = new();

    // Store buttons to update state
    private readonly Dictionary<NetEntity, Button> _droneButtons = new();

    public DroneConsoleWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        NavRadar.OnRadarClick += (coords) => OnRadarOrder?.Invoke(coords);

        SelectAllBtn.OnPressed += _ =>
        {
            foreach (var key in _droneButtons.Keys) _selectedDrones.Add(key);
            RefreshButtonVisuals();
        };

        DeselectAllBtn.OnPressed += _ =>
        {
            _selectedDrones.Clear();
            RefreshButtonVisuals();
        };
    }

    public HashSet<NetEntity> GetSelectedDrones() => _selectedDrones;

    public void UpdateState(DroneConsoleBoundUserInterfaceState state)
    {
        NavRadar.UpdateState(state.NavState);
        NavRadar.UpdateState(state.IFFState);

        // Rebuild list if changed (Naive approach, usually we differ)
        // For simplicity, we clear and rebuild if count matches but we don't check names.
        // In prod, check if dictionary keys match exactly to avoid flicker.
        if (_droneButtons.Count != state.LinkedDrones.Count || !_droneButtons.Keys.All(k => state.LinkedDrones.Contains(k)))
        {
            DroneListContainer.DisposeAllChildren();
            _droneButtons.Clear();

            int index = 1;
            foreach (var netEnt in state.LinkedDrones)
            {
                var btn = new Button
                {
                    Text = $"{index++}",
                    ToggleMode = true,
                    Pressed = _selectedDrones.Contains(netEnt)
                };

                btn.OnPressed += (args) =>
                {
                    if (btn.Pressed) _selectedDrones.Add(netEnt);
                    else _selectedDrones.Remove(netEnt);
                };

                _droneButtons[netEnt] = btn;
                DroneListContainer.AddChild(btn);
            }
        }
    }

    private void RefreshButtonVisuals()
    {
        foreach (var (netEnt, btn) in _droneButtons)
        {
            btn.Pressed = _selectedDrones.Contains(netEnt);
        }
    }
}
